const topRatedProduct = [{
    id:1,
    image:'./Images/topRatedGazebo.webp',
    rating:5,
    category:'topRated',
    description:'EROMMY 3 x 3.6m Hardtop Gazebo, Galvanized Steel Double Roof Metal Garden Gazebo',
    price:'£799.99',
     button:'Check It Out',
},
{
    id:2,
    image:'./Images/topRatedTent.webp',
    rating:5,
    category:'topRated',
    description:'Makita DLM532Z Twin 18V (36V) Li-ion LXT 53cm Brushless Lawn Mower - Batteries and Charger Not Included',
    price:'£901.05',
     button:'Check It Out',
},
{
    id:3,
    image:'./Images/topRatedRobotLawnmower.webp',
    rating:5,
    category:'topRated',
    description:'`10 x 8` Inflatable Tent for Camping, 6-8 People Blow up Tent, 4 Season Inflatable House with Stove Jack',
    price:'£727.44',
     button:'Check It Out',
},

{
    id:4,
    image:'./Images/topRatedGardenSwingSet.webp',
    rating:5,
    category:'topRated',
    description:'Backyard Discovery Cedar Cove 100% Cedar Wood Swing Set | Outdoor Playground for Kids',
    price:'£1,499',
    button:'Check It Out',
}];

const highlyRecommendedProduct = [{
    id:1,
    image:'./Images/topRatedGardenSwingSet.webp',
    rating:5,
    description:'EROMMY 3 x 3.6m Hardtop Gazebo, Galvanized Steel Double Roof Metal Garden Gazebo',
    price:'£799.99',
    category:'highly recommended',
    button:'Check It Out',
},
{
    id:2,
    image:'./Images/topRatedRobotLawnmower.webp',
    rating:5,
    description:'Makita DLM532Z Twin 18V (36V) Li-ion LXT 53cm Brushless Lawn Mower - Batteries and Charger Not Included',
    price:'£901.05',
    category:'highly recommended',
    button:'Check It Out',
},
{
    id:3,
    image:'./Images/topRatedTent.webp',
    rating:5,
    description:'`10 x 8` Inflatable Tent for Camping, 6-8 People Blow up Tent, 4 Season Inflatable House with Stove Jack',
    price:'£727.44',
    category:'highly recommended',
    button:'Check It Out',
},

{
    id:4,
    image:'./Images/topRatedGazebo.webp',
    rating:5,
    description:'Backyard Discovery Cedar Cove 100% Cedar Wood Swing Set | Outdoor Playground for Kids',
    price:'£1,499',
    category:'highly recommended',
    button:'Check It Out',
},{
    id:5,
    image:'./Images/topRatedGardenSwingSet.webp',
    rating:5,
    description:'EROMMY 3 x 3.6m Hardtop Gazebo, Galvanized Steel Double Roof Metal Garden Gazebo',
    price:'£799.99',
    category:'highly recommended',
    button:'Check It Out',
},
{
    id:6,
    image:'./Images/topRatedRobotLawnmower.webp',
    rating:5,
    description:'Makita DLM532Z Twin 18V (36V) Li-ion LXT 53cm Brushless Lawn Mower - Batteries and Charger Not Included',
    price:'£901.05',
    category:'highly recommended',
    button:'Check It Out',
},
{
    id:7,
    image:'./Images/topRatedTent.webp',
    rating:5,
    description:'`10 x 8` Inflatable Tent for Camping, 6-8 People Blow up Tent, 4 Season Inflatable House with Stove Jack',
    price:'£727.44',
    category:'highly recommended',
    button:'Check It Out',
},

{
    id:8,
    image:'./Images/topRatedGazebo.webp',
    rating:5,
    description:'Backyard Discovery Cedar Cove 100% Cedar Wood Swing Set | Outdoor Playground for Kids',
    price:'£1,499',
    category:'highly recommended',
    button:'Check It Out',
},{
    id:9,
    image:'./Images/topRatedGardenSwingSet.webp',
    rating:5,
    description:'EROMMY 3 x 3.6m Hardtop Gazebo, Galvanized Steel Double Roof Metal Garden Gazebo',
    price:'£799.99',
    category:'highly recommended',
    button:'Check It Out',
},
{
    id:10,
    image:'./Images/topRatedRobotLawnmower.webp',
    rating:5,
    description:'Makita DLM532Z Twin 18V (36V) Li-ion LXT 53cm Brushless Lawn Mower - Batteries and Charger Not Included',
    price:'£901.05',
    category:'highly recommended',
    button:'Check It Out',
},
{
    id:11,
    image:'./Images/topRatedTent.webp',
    rating:5,
    description:'`10 x 8` Inflatable Tent for Camping, 6-8 People Blow up Tent, 4 Season Inflatable House with Stove Jack',
    price:'£727.44',
    category:'highly recommended',
    button:'Check It Out',
},

{
    id:12,
    image:'./Images/topRatedGazebo.webp',
    rating:5,
    description:'Backyard Discovery Cedar Cove 100% Cedar Wood Swing Set | Outdoor Playground for Kids',
    price:'£1,499',
    category:'highly recommended',
    button:'Check It Out',
},
]

